var aNavContentData = [
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC91",
			price:"1791"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC93",
			price:"1793"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
];

var aCateContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-4"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-4"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-5"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-6"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机3-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机3-2"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-1"
		}
	]
]