var aNavContentData = [
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC91",
			price:"1791"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC93",
			price:"1793"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
]